### ISSUE TITLE
Invalid Frame Size

### ISSUE THREAD

**Issue by niteshsinha** [Thriftpy/thriftpy#266]
I am trying to connect to an HBase installation via thrift api. making use of happybase library.

I am getting the following error:
`

> Traceback (most recent call last):
>   File "test.py", line 5, in <module>
>     x,y = table.scan()
>   File "/tmp/tempvirtual/venv/lib/python2.7/site-packages/happybase/table.py", line 381, in scan
>     self.name, scan, {})
>   File "/tmp/tempvirtual/venv/lib/python2.7/site-packages/thriftpy/thrift.py", line 198, in _req
>     return self._recv(_api)
>   File "/tmp/tempvirtual/venv/lib/python2.7/site-packages/thriftpy/thrift.py", line 210, in _recv
>     fname, mtype, rseqid = self._iprot.read_message_begin()
>   File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6325)
>   File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1546)
>   File "thriftpy/transport/buffered/cybuffered.pyx", line 65, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_read (thriftpy/transport/buffered/cybuffered.c:1881)
>   File "thriftpy/transport/buffered/cybuffered.pyx", line 69, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.read_trans (thriftpy/transport/buffered/cybuffered.c:1948)
>   File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
>   File "/tmp/tempvirtual/venv/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 108, in read
>     buff = self.sock.recv(sz)
> socket.error: [Errno 104] Connection reset by peer

`

The thrift server seem to be running, but i see an error in its log 
`
2016-12-02 01:53:26,551 ERROR [Thread-7] server.THsHaServer: Read an invalid frame size of -2147418111. Are you using TFramedTransport on the client side?
`

**Comment by aisk** [comment]
Please report the issue to happybase directly.
